# Site settings
title: Phil Lang
email: plangphoto@gmail.com
description: Hello, I'm Phil. I'm a Web Developer and Creative Producer based in London. I'm a creative at heart. I'm also a bit of a data and privacy nerd. I aim to wield tech for good.
image: /img/profile.jpg
url: https://langp.me # the base hostname & protocol for your site
enforce_ssl: www.langp.me   # without any protocol
twitter_username: langphil
future: true # show posts with any date when published


# Build settings
markdown: kramdown
permalink: pretty

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Phil Lang
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

# Gems
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/blog/page/:num"
